const GD = window.GameData;
const SD = window.StoryData;
const SAVE_KEY = 'night-ledger-prototype-v1';
const SAVE_VERSION = 1;
const TESTER_MODE = new URLSearchParams(location.search).get('tester') === '1';
let storageMode = 'local';
let memorySave = null;
function storageGet(key){try{return window.localStorage.getItem(key)}catch(e){storageMode='memory';console.warn('Local storage unavailable; using session memory fallback.',e);return memorySave}}
function storageSet(key,value){try{window.localStorage.setItem(key,value);storageMode='local';return true}catch(e){storageMode='memory';memorySave=value;console.warn('Local storage unavailable; save kept for this open session only.',e);return false}}
function storageRemove(key){try{window.localStorage.removeItem(key)}catch(e){memorySave=null;storageMode='memory'}}
let state;let currentScreen='packs';let modalOpen=false;let storyQueue=[];let activeStory=null;let activeStoryPage=0;let lastTick=performance.now();let lastRender=0;let combatSecondBucket=0;let lastVisibilityAt=Date.now();
const screen=document.getElementById('screen');const modalRoot=document.getElementById('modal-root');const toastRoot=document.getElementById('toast-root');
function uid(prefix='c'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}function sum(arr){return arr.reduce((a,b)=>a+b,0)}function now(){return Date.now()}
function initialState(){return{version:SAVE_VERSION,createdAt:now(),lastSavedAt:now(),prestigeCount:0,resolveBonus:0,gold:0,intel:0,whispers:25,unlocks:{whispers:true,gold:false,intel:false,hideout:false,syndicate:false},hideoutLevel:1,hideoutBuild:null,currentOperation:1,highestCleared:0,opEntryFlags:{},battle:{mode:'push',encounter:1,enemy:null,targetFailed:false,momentumStacks:0,lastKillAt:0,paused:false},inventory:[],deck:[],syndicate:[],discovered:[],holoSeen:[],storySeen:[],freeStreetPack:true,firstPackOpened:false,awaitingFinale:false,prestigeReady:false,settings:{reducedMotion:false,sound:false},tutorial:{pack:false,operation:false,hideoutNav:false,hideoutUpgrade:false,syndicateNav:false},stats:{totalKills:0,targetsKilled:0,packsOpened:0,cardsSeen:0,holosSeen:0,goldEarned:0,intelEarned:0,whispersEarned:25}}}
function load(){const raw=storageGet(SAVE_KEY);if(!raw){state=initialState();currentScreen='packs';setTimeout(()=>{enqueueStory(SD.opening);enqueueStory(SD.system.whispers);enqueueStory(SD.firstPack)},200);return}try{state=JSON.parse(raw);migrateState();applyOfflineProgress();currentScreen=state.firstPackOpened?'battle':'packs'}catch(e){console.error(e);state=initialState();toast('Save could not be read. A new game was started.')}}
function migrateState(){const fresh=initialState();state=Object.assign(fresh,state||{});state.unlocks=Object.assign(fresh.unlocks,state.unlocks||{});state.battle=Object.assign(fresh.battle,state.battle||{});state.settings=Object.assign(fresh.settings,state.settings||{});state.tutorial=Object.assign(fresh.tutorial,state.tutorial||{});state.stats=Object.assign(fresh.stats,state.stats||{});state.inventory||=[];state.deck||=[];state.syndicate||=[];state.discovered||=[];state.holoSeen||=[];state.storySeen||=[];state.opEntryFlags||={}}
function save(){state.lastSavedAt=now();storageSet(SAVE_KEY,JSON.stringify(state))}
function getDef(inst){return GD.CARD_MAP[inst.defId]}function getInstance(id){return state.inventory.find(c=>c.uid===id)}function deckInstances(){return state.deck.map(getInstance).filter(Boolean)}function syndicateInstances(){return state.syndicate.map(getInstance).filter(Boolean)}
function isSyndicateDef(def){return def?.ability?.zone==='syndicate'}function isOperationDef(def){return !def?.ability||def.ability.zone==='operation'}
function gameCardMarkup(inst,opts={}){if(!inst)return'';const def=getDef(inst),td=GD.tierData(inst.tier),compact=!!opts.compact,showNew=opts.showNew??!!inst.isNew,showLevel=opts.showLevel??true;const ability=def?.ability?`<div class="game-card-ability"><b>${escapeHtml(def.ability.name)}</b>${escapeHtml(def.ability.text)}</div>`:'';const lore=def?.lore?`<div class="game-card-lore">${escapeHtml(def.lore)}</div>`:'';return `<div class="game-card ${compact?'compact':''} ${inst.holo?'holo':''}" style="border-color:${td.accent}">${inst.holo?'<span class="holo-tag">HOLO</span>':''}${showNew?'<span class="new-tag">NEW</span>':''}<div class="game-card-head"><div class="game-card-name">${escapeHtml(def.name)}</div><div class="game-card-deck" style="color:${td.accent}">${td.name.toUpperCase()} DECK</div></div><div class="game-card-art">[ CARD ART TBD ]</div><div class="game-card-bottom">${ability}${lore}${showLevel?`<div class="game-card-level">LV ${inst.level}</div>`:''}<div class="game-card-dps">DPS ${GD.formatNum(inst.baseDps)}</div></div></div>`}
function deckCardGridMarkup(cards,total=10,opts={}){const allowLevel=opts.allowLevel!==false;return Array.from({length:total},(_,i)=>{const inst=cards[i];if(!inst)return`<div class="deck-card-cell empty">EMPTY</div>`;const cost=inst.level<GD.CARD_LEVEL_CAP?GD.cardLevelCost(inst.tier,inst.level):0;const levelLabel=inst.level>=GD.CARD_LEVEL_CAP?'MAX':`LV+ ${GD.formatNum(cost)}`;return `<div class="deck-card-cell"><button class="deck-card-tap" data-card-detail="${inst.uid}" aria-label="View ${escapeHtml(getDef(inst)?.name||'card')}">${gameCardMarkup(inst,{compact:true,showNew:false})}</button>${allowLevel?`<button class="deck-level-btn" data-deck-level="${inst.uid}" ${state.gold<cost||inst.level>=GD.CARD_LEVEL_CAP?'disabled':''}>${levelLabel}</button>`:''}</div>`}).join('')}
function effectTotals(){const syn=syndicateInstances(),deck=deckInstances(),totals={architect:0,broker:0,appraiser:0,salvager:0,bookkeeper:0,informant:0,hideoutKeeper:0,sabotage:0,insideMan:0,contractInsight:0,shortcut:0};syn.forEach(inst=>{const a=getDef(inst)?.ability;if(!a)return;switch(a.name){case'Architect':totals.architect+=a.value;break;case'Broker':totals.broker+=a.value;break;case'Appraiser':totals.appraiser+=a.value;break;case'Salvager':totals.salvager+=a.value;break;case'Bookkeeper':totals.bookkeeper+=a.value;break;case'Informant':totals.informant+=a.value;break;case'Hideout Keeper':totals.hideoutKeeper+=a.value;break}});deck.forEach(inst=>{const a=getDef(inst)?.ability;if(!a)return;switch(a.name){case'Sabotage':totals.sabotage+=a.value;break;case'Inside Man':totals.insideMan+=a.value;break;case'Contract Insight':totals.contractInsight+=a.value;break;case'Shortcut':totals.shortcut+=a.value;break}});totals.architect=Math.min(.40,totals.architect);totals.broker=Math.min(.25,totals.broker);totals.appraiser=Math.min(.25,totals.appraiser);totals.bookkeeper=Math.min(.75,totals.bookkeeper);totals.informant=Math.min(.50,totals.informant);totals.salvager=Math.min(1,totals.salvager);totals.hideoutKeeper=Math.min(GD.MAX_OFFLINE_HOURS-GD.BASE_OFFLINE_HOURS,totals.hideoutKeeper);totals.sabotage=Math.min(.25,totals.sabotage);totals.insideMan=Math.min(3,Math.floor(totals.insideMan));totals.contractInsight=Math.min(.50,totals.contractInsight);totals.shortcut=Math.min(.20,totals.shortcut);return totals}
function offlineCapHours(){return GD.BASE_OFFLINE_HOURS+effectTotals().hideoutKeeper}function whisperRate(){return GD.whisperRatePerHour(state.hideoutLevel)}function packCost(tier){return Math.max(1,Math.round(GD.packBaseCost(tier)*(1-effectTotals().broker)))}function addGold(v){if(v<=0)return;state.gold+=v;state.stats.goldEarned+=v}function addIntel(v){if(v<=0)return;state.intel+=v;state.stats.intelEarned+=v}function addWhispers(v){if(v<=0)return;state.whispers+=v;state.stats.whispersEarned+=v}