function autoFillDeck(){const candidates=state.inventory.filter(c=>isOperationDef(getDef(c))).sort((a,b)=>GD.cardDps(b)-GD.cardDps(a));state.deck=candidates.slice(0,10).map(c=>c.uid)}
function autoFillSyndicate(){const slots=GD.syndicateSlots(state.hideoutLevel),candidates=state.inventory.filter(c=>isSyndicateDef(getDef(c))),seen=new Set(),chosen=[];candidates.sort((a,b)=>b.tier-a.tier).forEach(c=>{const n=getDef(c).ability.name;if(chosen.length<slots&&!seen.has(n)){chosen.push(c.uid);seen.add(n)}});candidates.forEach(c=>{if(chosen.length<slots&&!chosen.includes(c.uid))chosen.push(c.uid)});state.syndicate=chosen.slice(0,slots);save();render()}
function enterCurrentOperation(){const op=state.currentOperation;if(state.opEntryFlags[op])return;state.opEntryFlags[op]=true;const skip=effectTotals().insideMan;state.battle.encounter=Math.min(24,1+skip)}
function spawnEnemy(){enterCurrentOperation();const op=state.currentOperation,encounter=state.battle.encounter,target=encounter>=25;let maxHp=target?GD.targetHp(op):GD.normalEnemyHp(op);if(target)maxHp*=1-effectTotals().sabotage;state.battle.enemy={id:uid('e'),name:GD.enemyName(op,encounter,target),target,hp:maxHp,maxHp,spawnedAt:now(),deadline:target?now()+30000:null}}
function estimateDeckDps(target=false,hpRatio=1){let total=0;const elapsed=state.battle.enemy?(now()-state.battle.enemy.spawnedAt)/1000:0;deckInstances().forEach(inst=>{const def=getDef(inst);let d=GD.cardDps(inst);const a=def.ability;if(a){if(a.name==='Contract Killer'&&target)d*=1+a.value;if(a.name==='Opening Strike'&&hpRatio>.8)d*=1+a.value;if(a.name==='Finisher'&&hpRatio<.3)d*=1+a.value;if(a.name==='Patient Killer')d*=1+Math.min(.50,a.value*elapsed)}total+=d});const momentumEffects=deckInstances().map(c=>getDef(c)?.ability).filter(a=>a?.name==='Momentum'),momentumPerStack=Math.min(.05,sum(momentumEffects.map(a=>a.value))),momentumBonus=Math.min(.50,momentumPerStack*state.battle.momentumStacks);return total*(1+momentumBonus)*(1+(state.resolveBonus||0))}
function procCombatSecond(){const enemy=state.battle.enemy;if(!enemy)return;const target=enemy.target,hpRatio=enemy.hp/enemy.maxHp;let bonusDamage=0,executeChance=0;deckInstances().forEach(inst=>{const a=getDef(inst).ability;if(!a)return;const cdps=GD.cardDps(inst);if(a.name==='Double Strike'&&Math.random()<a.value)bonusDamage+=cdps;if(a.name==='Eviscerate'&&Math.random()<a.value){bonusDamage+=cdps*5;floatingHit('EVISCERATE')}if(a.name==='Execute')executeChance+=a.value});executeChance=Math.min(.10,executeChance);const threshold=target?.05:.15;if(hpRatio<=threshold&&Math.random()<executeChance){enemy.hp=0;floatingHit('EXECUTE');return}enemy.hp-=bonusDamage}
function floatingHit(text){const ec=document.querySelector('.enemy-card');if(!ec)return;const el=document.createElement('div');el.className='float-hit';el.textContent=text;ec.appendChild(el);setTimeout(()=>el.remove(),700)}
function handleEnemyKilled(){const enemy=state.battle.enemy;if(!enemy)return;const op=state.currentOperation,e=effectTotals(),mult=enemy.target?GD.targetRewardMultiplier():1;let gold=GD.normalGold(op)*mult*(1+e.bookkeeper),intel=GD.normalIntel(op)*mult*(1+e.informant);if(enemy.target)intel*=1+e.contractInsight;addGold(gold);addIntel(intel);state.stats.totalKills++;unlockGold();state.battle.momentumStacks=Math.min(10,state.battle.momentumStacks+1);state.battle.lastKillAt=now();if(enemy.target){state.stats.targetsKilled++;state.highestCleared=Math.max(state.highestCleared,op);if(op===1)unlockIntelAndHideout();if(SD.operations[op])enqueueStory(SD.operations[op]);addWhispers(packCost(GD.tierForHideout(state.hideoutLevel))*.05);if(op>=100){state.currentOperation=100;state.battle.enemy=null;state.battle.encounter=25;state.battle.paused=true;if(state.hideoutLevel>=20)triggerFinale();else{state.awaitingFinale=true;toast('Operation 100 cleared. Complete Hideout 20 to open the final door.')}}else{state.currentOperation=op+1;state.battle.encounter=1;state.battle.enemy=null;state.battle.targetFailed=false;state.battle.mode='push'}}else{let next=state.battle.encounter;if(state.battle.mode==='farm')next=24;else{next++;if(next<25&&Math.random()<e.shortcut){next++;toast('Shortcut: skipped an encounter.')}next=Math.min(25,next)}state.battle.encounter=next;state.battle.enemy=null}save()}
function failTarget(){const op=state.currentOperation;state.battle.targetFailed=true;state.battle.mode='farm';state.battle.encounter=24;state.battle.enemy=null;toast(`${GD.enemyName(op,25,true)} escaped. Biding your time at Encounter 24.`);save();render()}
function retryTarget(){state.battle.mode='push';state.battle.targetFailed=false;state.battle.encounter=25;state.battle.enemy=null;spawnEnemy();save();render()}
function beginOperation(){if(!state.firstPackOpened||!deckInstances().length)return;state.battle.paused=false;state.tutorial.operation=true;state.battle.encounter=Math.max(1,state.battle.encounter||1);state.battle.enemy=null;spawnEnemy();save();render()}
function setBattleMode(mode){state.battle.mode=mode;if(mode==='farm'){state.battle.encounter=24;state.battle.enemy=null}else if(state.battle.targetFailed){retryTarget();return}save();render()}
function triggerFinale(){if(state.prestigeReady)return;state.prestigeReady=true;state.awaitingFinale=false;save();enqueueStory(SD.finale)}
function performPrestige(){const preserved={prestigeCount:(state.prestigeCount||0)+1,resolveBonus:.05*((state.prestigeCount||0)+1),discovered:[...state.discovered],holoSeen:[...state.holoSeen],storySeen:[...state.storySeen],settings:{...state.settings}};state=initialState();state.prestigeCount=preserved.prestigeCount;state.resolveBonus=preserved.resolveBonus;state.discovered=preserved.discovered;state.holoSeen=preserved.holoSeen;state.storySeen=preserved.storySeen;state.settings=preserved.settings;state.whispers=25;state.stats.whispersEarned=25;currentScreen='packs';modalOpen=false;modalRoot.innerHTML='';save();render();toast(`Prestige ${state.prestigeCount}: Resolve +${Math.round(state.resolveBonus*100)}% DPS`)}
function startHideoutUpgrade(){if(state.hideoutBuild||state.hideoutLevel>=20)return;state.tutorial.hideoutUpgrade=true;clearTutorialCoach();const next=state.hideoutLevel+1,intel=GD.hideoutIntelCost(next),req=GD.hideoutOperationReq(next);if(state.highestCleared<req)return toast(`Clear Operation ${req} first.`);if(state.intel<intel)return toast('Not enough Intel.');state.intel-=intel;const mins=GD.hideoutBuildMinutes(next)*(1-effectTotals().architect);state.hideoutBuild={targetLevel:next,startedAt:now(),endsAt:now()+mins*60000,baseMinutes:GD.hideoutBuildMinutes(next)};save();render()}
function completeHideoutIfReady(force=false){const b=state.hideoutBuild;if(!b)return;if(!force&&now()<b.endsAt)return;state.hideoutLevel=b.targetLevel;state.hideoutBuild=null;if(state.hideoutLevel>=3&&!state.unlocks.syndicate){state.unlocks.syndicate=true;enqueueStory(SD.system.syndicate)}if(SD.hideout[state.hideoutLevel])enqueueStory(SD.hideout[state.hideoutLevel]);const unlockedTier=GD.TIERS.find(t=>t.unlock===state.hideoutLevel);if(unlockedTier)toast(`${unlockedTier.name} pack unlocked.`);if(state.hideoutLevel>=20&&state.awaitingFinale&&state.highestCleared>=100)triggerFinale();save();render()}
function levelCard(id,count=1){const inst=getInstance(id);if(!inst)return;const scrollY=window.scrollY;for(let i=0;i<count;i++){if(inst.level>=GD.CARD_LEVEL_CAP)break;const cost=GD.cardLevelCost(inst.tier,inst.level);if(state.gold<cost)break;state.gold-=cost;inst.level++}save();render();requestAnimationFrame(()=>window.scrollTo(0,scrollY))}
function canSell(inst){if(state.deck.includes(inst.uid)||state.syndicate.includes(inst.uid))return false;return state.inventory.filter(c=>c.defId===inst.defId).length>1}
function sellRefund(inst){const rel=inst.tier/Math.max(1,inst.sourcePackTier||inst.tier),base=(inst.sourcePackCost||GD.packBaseCost(inst.sourcePackTier||inst.tier))*.02*(.5+.5*rel);return Math.round(base*(1+effectTotals().salvager))}
function sellCard(id){const inst=getInstance(id);if(!inst||!canSell(inst))return;const refund=sellRefund(inst);state.inventory=state.inventory.filter(c=>c.uid!==id);addWhispers(refund);save();render();toast(`Sold duplicate for ${GD.formatNum(refund)} Whispers.`)}
function equipDeck(id){const inst=getInstance(id),def=getDef(inst);if(!inst||!isOperationDef(def))return;if(state.deck.includes(id))state.deck=state.deck.filter(x=>x!==id);else{if(state.deck.length>=10)return toast('Operation Deck is full.');state.syndicate=state.syndicate.filter(x=>x!==id);state.deck.push(id)}save();render()}
function equipSyndicate(id){if(!state.unlocks.syndicate)return toast('Syndicate unlocks at Hideout 3.');const inst=getInstance(id),def=getDef(inst);if(!inst||!isSyndicateDef(def))return;if(state.syndicate.includes(id))state.syndicate=state.syndicate.filter(x=>x!==id);else{const slots=GD.syndicateSlots(state.hideoutLevel);if(state.syndicate.length>=slots)return toast('Syndicate is full.');state.deck=state.deck.filter(x=>x!==id);state.syndicate.push(id)}save();render()}