function clearTutorialCoach(){document.querySelectorAll('.tutorial-target').forEach(el=>el.classList.remove('tutorial-target'));document.querySelectorAll('.tutorial-parent').forEach(el=>el.classList.remove('tutorial-parent'));document.getElementById('tutorial-dim')?.remove();document.getElementById('tutorial-coach')?.remove()}
function showTutorialSpotlight(selector,text){clearTutorialCoach();const target=document.querySelector(selector);if(!target||target.disabled)return false;const dim=document.createElement('div');dim.id='tutorial-dim';dim.className='tutorial-dim';document.body.appendChild(dim);target.classList.add('tutorial-target');const stackingParent=target.closest('.bottom-nav,.topbar');if(stackingParent)stackingParent.classList.add('tutorial-parent');const coach=document.createElement('div');coach.id='tutorial-coach';coach.className='tutorial-coach';coach.innerHTML=`<b>${escapeHtml(text)}</b><span class="tutorial-dagger"></span>`;document.body.appendChild(coach);const rect=target.getBoundingClientRect(),cw=Math.min(280,window.innerWidth-28);let left=Math.max(14,Math.min(window.innerWidth-cw-14,rect.left+rect.width/2-cw/2)),top;const below=rect.bottom+70;if(below+90<window.innerHeight)top=below;else top=Math.max(14,rect.top-120);coach.style.left=`${left}px`;coach.style.top=`${top}px`;const dagger=coach.querySelector('.tutorial-dagger');if(top>rect.bottom){dagger.style.top='-43px';dagger.style.left=`${Math.max(24,Math.min(cw-30,rect.left+rect.width/2-left-4))}px`}else{dagger.style.bottom='-43px';dagger.style.left=`${Math.max(24,Math.min(cw-30,rect.left+rect.width/2-left-4))}px`;dagger.style.transform='rotate(222deg)'}return true}
function maybeShowTutorial(){clearTutorialCoach();if(modalOpen||activeStory)return;if(!state.firstPackOpened&&currentScreen==='packs'&&!state.tutorial.pack&&state.storySeen.includes('first_pack')){showTutorialSpotlight('[data-open-pack="1"]','Open your first pack to recruit operatives.');return}if(state.firstPackOpened&&state.battle.paused&&currentScreen==='battle'&&!state.tutorial.operation){showTutorialSpotlight('#begin-operation','Tap here when you are ready to begin your first Operation.');return}if(state.unlocks.hideout&&!state.tutorial.hideoutNav&&currentScreen!=='hideout'){showTutorialSpotlight('.bottom-nav [data-nav="hideout"]','The Hideout is available. Tap here to rebuild it.');return}if(state.unlocks.hideout&&currentScreen==='hideout'&&!state.tutorial.hideoutUpgrade){if(showTutorialSpotlight('#hideout-upgrade','When the requirements are met, tap here to rebuild the next Hideout level.'))return}if(state.unlocks.syndicate&&!state.tutorial.syndicateNav&&currentScreen!=='syndicate')showTutorialSpotlight('.bottom-nav [data-nav="syndicate"]','The Syndicate is available. Tap here to assign support operatives.')}
function bindCommonActions(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelectorAll('[data-card-detail]').forEach(b=>b.onclick=()=>showCardDetail(b.dataset.cardDetail));document.querySelectorAll('[data-deck-level]').forEach(b=>b.onclick=()=>levelCard(b.dataset.deckLevel,1))}
function navigate(nav){if(nav==='hideout'&&!state.unlocks.hideout)return toast('Clear Operation 1 to reclaim the Hideout.');if(nav==='syndicate'&&!state.unlocks.syndicate)return toast('Syndicate unlocks at Hideout 3.');clearTutorialCoach();if(nav==='hideout')state.tutorial.hideoutNav=true;if(nav==='syndicate')state.tutorial.syndicateNav=true;currentScreen=nav;save();render()}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function onFirstKillStory(){}
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();lastVisibilityAt=now()}else{const elapsed=(now()-lastVisibilityAt)/1000;if(state.battle.enemy?.target&&state.battle.enemy.deadline)state.battle.enemy.deadline+=elapsed*1000;if(elapsed>30){state.lastSavedAt=lastVisibilityAt;applyOfflineProgress();save();render()}}});
window.addEventListener('beforeunload',save);setInterval(save,3000);
window.__NL={getState:()=>state,openPack,navigate,devAction,beginOperation,retryTarget,startHideoutUpgrade,completeHideoutIfReady,levelCard,equipDeck,equipSyndicate,autoFillDeck,autoFillSyndicate,packCost,effectTotals,save};
load();render();bindCommonActions();requestAnimationFrame(tick);