(() => {
  const V=window.LRV6=window.LRV6||{};
  V.HELP={
    battle:{title:'Operations',text:'Follow the trail through each Operation. Assassinate to press forward, or Bide Your Time when you need more time to build strength.'},
    hideout:{title:'The Hideout',text:'Use Intel to rebuild the Hideout. Each restored level brings more of the old network back within reach.'},
    packs:{title:'Booster Packs',text:'Spend Whispers to open Booster Packs and recruit new operatives.'},
    deck:{title:'Operation Deck',text:'Choose the ten operatives you want to send into Operations. Tap a card to inspect it, or hold it to choose a replacement.'},
    library:{title:'Library',text:'Every operative you have discovered is kept here. Search by name or narrow the list to find the card you want.'},
    syndicate:{title:'The Syndicate',text:'Some operatives are more useful behind the scenes. Assign them here to strengthen the Hideout and support your work in the field.'},
    settings:{title:'More',text:'Adjust the game audio and revisit story chapters here.'}
  };
  V.BACK='assets/card-art/street-deck-back.png?v=6';
  V.libFilter=0;V.libSort='rarity';V.libSearch='';V.swapTarget=null;V.syndicatePick=false;V.copyIndex={};
  state.uiHelpSeenV6 ||= Object.assign({},state.uiHelpSeen||{});state.uiHelpSeen||={};
  ['battle','hideout','packs','deck','library','syndicate','settings'].forEach(k=>state.uiHelpSeen[k]=true);save();
  V.showHelp=function(key){if(modalOpen||activeStory||state.uiHelpSeenV6?.[key])return;const item=V.HELP[key];if(!item)return;state.uiHelpSeenV6[key]=true;save();modalOpen=true;modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal info-modal"><div class="kicker">${escapeHtml(item.title.toUpperCase())}</div><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.text)}</p><button class="btn primary" id="help-v6-close" style="width:100%">CONTINUE</button></div></div>`;document.getElementById('help-v6-close').onclick=()=>{modalRoot.innerHTML='';modalOpen=false;render();};};
  const prevRender=render;render=function(){prevRender();const scroll=currentScreen==='deck'||currentScreen==='library';document.body.classList.toggle('screen-scroll',scroll);document.body.classList.toggle('screen-fixed',!scroll);setTimeout(()=>V.showHelp(currentScreen),0);};
  renderSettings=function(){const narrative=state.storySeen.map(id=>findStoryById(id)).filter(Boolean).filter(s=>!s.id.startsWith('sys_')),numbered=narrative.map((s,i)=>({s,n:i+1})),recent=numbered.slice(-4),tester=TESTER_MODE?`<div class="pixel-panel"><div class="panel-title"><h3>TESTER</h3></div><div class="dev-grid"><button class="btn ghost" data-dev="gold">+1M GOLD</button><button class="btn ghost" data-dev="intel">+1M INTEL</button><button class="btn ghost" data-dev="whispers">+1M WHISPERS</button><button class="btn ghost" data-dev="build">FINISH BUILD</button><button class="btn ghost" data-dev="kill">KILL ENEMY</button><button class="btn ghost" data-dev="clear">CLEAR OP</button><button class="btn danger" data-dev="reset">RESET SAVE</button></div></div>`:'';screen.innerHTML=`<div class="pixel-panel"><div class="panel-title"><h2 class="more-title">MORE</h2><small>SETTINGS</small></div><div class="settings-list"><div class="setting"><div><b>SOUND</b><div class="tiny">Card sounds.</div></div><button class="mini-btn" id="toggle-sound-v6">${state.settings.sound?'ON':'OFF'}</button></div><div class="setting"><div><b>MUSIC</b></div><button class="mini-btn" id="toggle-music-v6">${state.settings.music?'ON':'OFF'}</button></div><div class="setting"><div><b>REDUCED MOTION</b><div class="tiny">Use shorter card animations.</div></div><button class="mini-btn" id="toggle-motion-v6">${state.settings.reducedMotion?'ON':'OFF'}</button></div></div></div><div class="pixel-panel"><div class="panel-title"><h3>STORY LOG</h3><small>CHAPTERS</small></div><div class="story-log-compact">${recent.length?recent.map(({s,n})=>`<button class="story-entry" data-story-replay="${s.id}"><b>CHAPTER ${String(n).padStart(2,'0')} · ${escapeHtml(s.title)}</b><span class="story-chapter-num">${String(n).padStart(2,'0')}</span></button>`).join(''):'<div class="empty-state">NO CHAPTERS YET</div>'}</div></div>${tester}`;document.getElementById('toggle-sound-v6').onclick=()=>{state.settings.sound=!state.settings.sound;save();if(state.settings.sound)playUISoundV5?.('select');renderSettings();};document.getElementById('toggle-music-v6').onclick=()=>{state.settings.music=!state.settings.music;save();renderSettings();};document.getElementById('toggle-motion-v6').onclick=()=>{state.settings.reducedMotion=!state.settings.reducedMotion;save();renderSettings();};screen.querySelectorAll('[data-story-replay]').forEach(b=>b.onclick=()=>{const s=findStoryById(b.dataset.storyReplay);if(s)enqueueStory(s,true);});screen.querySelectorAll('[data-dev]').forEach(b=>b.onclick=()=>devAction(b.dataset.dev));};
  const oldUnlock=unlockIntelAndHideout;unlockIntelAndHideout=function(){const before=state.unlocks.hideout;oldUnlock();if(!before&&state.unlocks.hideout){state.uiHelpSeen.hideout=true;state.uiHelpSeenV6.hideout=false;save();}};
  const oldComplete=completeHideoutIfReady;completeHideoutIfReady=function(force=false){const before=state.unlocks.syndicate;oldComplete(force);if(!before&&state.unlocks.syndicate){state.uiHelpSeen.syndicate=true;state.uiHelpSeenV6.syndicate=false;save();}};
})();